nginx:
  build: nginx
  links:
    - server
  ports:
    - "80:80"
    - "443:443"
  environment:
    NODE_HOST: laptop-hooks.my-server.com

server:
  build: server
  ports:
    - "3000:3000"
  # volumes:
  #  - .:/src
  command: "node server/server.js"
