#!/bin/sh

cp default.conf.example default.conf

os=$(uname)
host=$NODE_HOST;
# : is 'do nothing' command. it emits the value, then tries to run it
: ${host:=laptop-hooks.my-server.com};

echo $host

if [ "$os" = "Linux" ]; then
  replace_host=s/HOST/$host/g
  sed -i "$replace_host" default.conf
else
  replace_host=s/HOST/$host/g
  perl -p -i -e "$replace_host" default.conf
fi

