#!/bin/sh

host=$NODE_HOST;
# : is 'do nothing' command. it emits the value, then tries to run it
: ${host:=laptop-hooks.my-server.com};

/bin/sed -i "s/ADDR/${SERVER_PORT_3000_TCP_ADDR}/" /etc/nginx/conf.d/default.conf
/bin/sed -i "s/PORT/${SERVER_PORT_3000_TCP_PORT}/" /etc/nginx/conf.d/default.conf
/bin/sed -i "s/HOST/$host/" /etc/nginx/conf.d/default.conf

nginx
